const guests = {
  "yzi7s6": "呂忠龍 一家",
  "6uizsg": "呂重慶 一家",
  "hk7p9r": "陳坤田 一家",
  "0zcd3v": "楊宏元 一家",
  "ihddzf": "楊秉學＆許惠慈",
  "yt21q3": "呂勇男 一家",
  "tew0c0": "楊畯安",
  "fl0g0y": "陳詩聖＆何秀玲",
  "k9vbcu": "陳詩淵 一家",
  "ors7gh": "鄭宇君",
  "x3tpla": "賴柔君",
  "9yuzyd": "陳力瑀",
  "d1k0k6": "黃映倫",
  "5mh8ds": "王惟緗",
  "oz5ki3": "林芳伃",
  "ksugf1": "呂柔慧",
  "ufqdib": "張虹儀",
  "9g0l0f": "王柏喬",
  "t2jgz2": "黃強圃",
  "9g6ue9": "高志杰",
  "gmw4m7": "康致嘉",
  "h4qsgx": "洪敦耀",
  "j0xupg": "張合",
  "fo3zi0": "陳智弘",
  "p6cgo6": "崔浩群",
  "5kvqy7": "詹清智",
  "kkhcwb": "許澤維",
  "yob7ze": "楊仁翔",
  "6otdo0": "王柏鈞",
  "xoti57": "賴禹辰",
  "oxx7az": "吳為霖",
  "sox9gw": "賴德寧",
  "paoqhd": "游國仁",
  "ci1hiv": "賴奕澄",
  "0fu7dm": "李胤翰",
  "6th946": "李冠億",
  "mid6vc": "Lars Meyer",
};

export default guests;